# General build informations
language: csharp
sudo: required
mono: none
dotnet: 2.2.104

# Define the jobs
jobs:
    include:
      - stage: "Build"
        script: 
        - dotnet build src/Rhisis.Core/ --framework netstandard2.0 --configuration Release
        - dotnet build src/Rhisis.Database/ --framework netstandard2.0 --configuration Release
        - dotnet build src/Rhisis.Business/ --framework netstandard2.0 --configuration Release
        - dotnet build src/Rhisis.Login/ --framework netcoreapp2.0 --configuration Release
        - dotnet build src/Rhisis.Cluster/ --framework netcoreapp2.0 --configuration Release
        - dotnet build src/Rhisis.World/ --framework netcoreapp2.0 --configuration Release
        - dotnet build src/Rhisis.API/ --framework netcoreapp2.0 --configuration Release
        - dotnet build src/Rhisis.CLI/ --framework netcoreapp2.0 --configuration Release
        name: "Rhisis Servers"

      - stage: "Tests"
        script: 
        - dotnet test test/Rhisis.Core.Test/
        - dotnet test test/Rhisis.Database.Test/
        - dotnet test test/Rhisis.Business.Tests/
        name: "Rhisis Tests"